project:
  type: book
  output-dir: docs

execute: 
  echo: true
  warning: false
  message: false
  
book:
  title: "Econometrics"
  chapters:
    - chapter0.qmd
    - chapter3.qmd
    
format:
  html:
    theme: [default]
    number-sections: false
