// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// chapter-3.cpp
doubles_matrix<> ols_r_(const doubles_matrix<>& y, const doubles_matrix<>& x);
extern "C" SEXP _hansen_ols_r_(SEXP y, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(ols_r_(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(y), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(x)));
  END_CPP11
}
// chapter-3.cpp
double influence_r_(const doubles_matrix<>& y, const doubles_matrix<>& x);
extern "C" SEXP _hansen_influence_r_(SEXP y, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(influence_r_(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(y), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(x)));
  END_CPP11
}
// chapter-4.cpp
doubles_matrix<> ols2_r_(const doubles_matrix<>& y, const doubles_matrix<>& x);
extern "C" SEXP _hansen_ols2_r_(SEXP y, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(ols2_r_(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(y), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(x)));
  END_CPP11
}
// chapter-4.cpp
doubles_matrix<> cls_r_(const doubles_matrix<>& y, const doubles_matrix<>& x);
extern "C" SEXP _hansen_cls_r_(SEXP y, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(cls_r_(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(y), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(x)));
  END_CPP11
}
// chapter-4.cpp
doubles_matrix<> ddk_r_(const doubles_matrix<>& y, const doubles_matrix<>& x, const doubles_matrix<>& z);
extern "C" SEXP _hansen_ddk_r_(SEXP y, SEXP x, SEXP z) {
  BEGIN_CPP11
    return cpp11::as_sexp(ddk_r_(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(y), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(x), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(z)));
  END_CPP11
}
// chapter-8.cpp
doubles_matrix<> ols3_r_(const doubles_matrix<>& y, const doubles_matrix<>& x);
extern "C" SEXP _hansen_ols3_r_(SEXP y, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(ols3_r_(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(y), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(x)));
  END_CPP11
}
// chapter-8.cpp
doubles_matrix<> cns_r_(const doubles_matrix<>& y, const doubles_matrix<>& x, const doubles_matrix<>& r);
extern "C" SEXP _hansen_cns_r_(SEXP y, SEXP x, SEXP r) {
  BEGIN_CPP11
    return cpp11::as_sexp(cns_r_(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(y), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(x), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(r)));
  END_CPP11
}
// chapter-8.cpp
doubles_matrix<> emd_r_(const doubles_matrix<>& y, const doubles_matrix<>& x, const doubles_matrix<>& r);
extern "C" SEXP _hansen_emd_r_(SEXP y, SEXP x, SEXP r) {
  BEGIN_CPP11
    return cpp11::as_sexp(emd_r_(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(y), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(x), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(r)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_hansen_cls_r_",       (DL_FUNC) &_hansen_cls_r_,       2},
    {"_hansen_cns_r_",       (DL_FUNC) &_hansen_cns_r_,       3},
    {"_hansen_ddk_r_",       (DL_FUNC) &_hansen_ddk_r_,       3},
    {"_hansen_emd_r_",       (DL_FUNC) &_hansen_emd_r_,       3},
    {"_hansen_influence_r_", (DL_FUNC) &_hansen_influence_r_, 2},
    {"_hansen_ols2_r_",      (DL_FUNC) &_hansen_ols2_r_,      2},
    {"_hansen_ols3_r_",      (DL_FUNC) &_hansen_ols3_r_,      2},
    {"_hansen_ols_r_",       (DL_FUNC) &_hansen_ols_r_,       2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_hansen(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
