# Generated by cpp11: do not edit by hand

ols_r_ <- function(y, x) {
  .Call(`_hansen_ols_r_`, y, x)
}

influence_r_ <- function(y, x) {
  .Call(`_hansen_influence_r_`, y, x)
}

ols2_r_ <- function(y, x) {
  .Call(`_hansen_ols2_r_`, y, x)
}

cls_r_ <- function(y, x) {
  .Call(`_hansen_cls_r_`, y, x)
}

ddk_r_ <- function(y, x, z) {
  .Call(`_hansen_ddk_r_`, y, x, z)
}

ols3_r_ <- function(y, x) {
  .Call(`_hansen_ols3_r_`, y, x)
}

cns_r_ <- function(y, x, r) {
  .Call(`_hansen_cns_r_`, y, x, r)
}

emd_r_ <- function(y, x, r) {
  .Call(`_hansen_emd_r_`, y, x, r)
}
